### ISSUE TITLE
Will typed_erlc support subtyping?

### ISSUE THREAD

**Issue by mheiber** [kvakvs/Ironclad#1]
(not a feature request, just curious)

I'm asking because it seems there are untagged unions (which makes me suspect the plan is to have subtyping) but the type-checking seems Hindley-Milner-style, which doesn't have subtyping.

Thanks for sharing this work.

**Comment by kvakvs** [comment]
H-M in the master branch is most likely gotta go. It was promising and i managed to modify H-M to support type unions and some basic subtyping checks and its complexity quickly went out of control. But the current work is in the `bidirectional-typing` branch and that's much closer to what modern Erlang type system is.

There is code for subtyping, for example a tuple with 1st atom element will be a subtype to same style record, as long as its fields are subtypes to corresponding record fields. https://github.com/kvakvs/typed_erlc/blob/bidirectional-typing/compiler/src/typing/subtyping.rs Same goes for functions to be subtypes of other functions (args and return types must be compatible).

**Comment by mheiber** [comment]
thanks!
